import "~/styles/globals.css";
import "@uploadthing/react/styles.css";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "./api/uploadthing/core";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs';
import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { Inter } from "next/font/google";
import {TopNav } from "./_components/topnav";
import { Toaster } from "~/components/ui/sonner"

const inter = Inter({
    subsets: ["latin"],
    variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create T3 Gallery",
  description: "Generated by a loyal subscriber to Theo on YouTube.",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});


export default function RootLayout({
  children,
  modal,
}: Readonly<{
        children: React.ReactNode;
        modal: React.ReactNode;
    }>) {
  return (
    <ClerkProvider>
            <html lang="en" className={`${geist.variable} `}>
                <NextSSRPlugin
                    /**
           * The `extractRouterConfig` will extract **only** the route configs
           * from the router to prevent additional information from being
           * leaked to the client. The data passed to the client is the same
           * as if you were to fetch `/api/uploadthing` directly.
           */
                    routerConfig={extractRouterConfig(ourFileRouter)}
                />
                <body className={`font-sans ${inter.variable} dark`}>
                    <div className="grid h-screen grid-rows-[auto,1fr]">
                        <TopNav />
                        <main className="overflow-y-scroll">{children}</main>
                    </div>
                    {modal}
                    <div id="modal-root" />
                    <Toaster />
                </body>
            </html>
    </ClerkProvider>
  );
}
