import "~/styles/globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs';
import { type Metadata } from "next";
import { Geist } from "next/font/google";
import {TopNav } from "./_components/topnav";

export const metadata: Metadata = {
  title: "Create T3 Gallery",
  description: "Generated by a loyal subscriber to Theo on YouTube.",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});


export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
            <html lang="en" className={`${geist.variable} `}>
                <body className="flex flex-col gap-4">
                    <TopNav />
                    {children}
                </body>
            </html>
    </ClerkProvider>
  );
}
